{% set name = "poligrain" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/poligrain-{{ version }}.tar.gz
  sha256: 0c9fb83c95faf52cfa912ee4fc9ab2f8206b6cba8b46a1a3bd406086e9add50e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.12
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - pip
  run:
    - python >=3.9,<3.12
    - netcdf4 >=1.6.5,<2.0.0
    - xarray >=2023.12.0,<2024.0.0
    - matplotlib-base >=3.8.2,<4.0.0
    - nbmake >=1.4.6,<2.0.0
    - pyproj >=3.6.1,<4.0.0
    - scipy >=1.12.0,<2.0.0
    - sparse
    - shapely

test:
  imports:
    - poligrain
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/OpenSenseAction/poligrain
  summary: Effortlessly plot and compare (rainfall) sensor data with point, line and grid geometry.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cchwala
